/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timeServer.h"
#include<time.h>

#define SPLIT_ADDRESS(s_addr) \
    ((s_addr) >> 24) & 0xFF, \
    ((s_addr) >> 16) & 0xFF, \
    ((s_addr) >>  8) & 0xFF, \
    ((s_addr)      ) & 0xFF

long *
get_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

	result = time(0);
	printf("Client Address: %hu.%hu.%hu.%hu:%d\n", SPLIT_ADDRESS(ntohl(rqstp->rq_xprt->xp_raddr.sin_addr.s_addr)),ntohs(rqstp->rq_xprt->xp_raddr.sin_port));
	return &result;
}
